import "@/styles/globals.css";
import { Metadata } from "next";
import { PropsWithChildren } from "react";
import { Bricolage_Grotesque } from "next/font/google";
import { Providers } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Morsenow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={font.className} suppressHydrationWarning>
      <body>
        <Providers>
          {children}
          <ThemeToggle />
        </Providers>
      </body>
    </html>
  );
}
